### ISSUE TITLE
使用字节的hertz框架是否更活跃

### ISSUE THREAD

**Issue by cucy** [GoSimplicity/AICoreOps#13]
如题？

**Comment by GoSimplicity** [comment]
> 如题？

go-zero的生态更加完善 各种解决方案也比较成熟 对比Kratos、hertz  综合考虑下来我们还是选择zero作为微服务框架

**Comment by GoSimplicity** [comment]
> 如题？

框架只是一种工具  只要能完成最后的目的 用什么框架其实是无所谓的

**Comment by auqf** [comment]
前端项目[AICoreOps-web](https://github.com/GoSimplicity/AICoreOps-web)怎么没用了？
